feat: fix server dockerfile

diff --git a/packages/server/Dockerfile b/packages/server/Dockerfile
--- a/packages/server/Dockerfile
+++ b/packages/server/Dockerfile
@@ -1,8 +1,33 @@
-FROM node:18
-RUN mkdir -p /usr/src/app
+FROM node:18-alpine AS builder
+
+ENV NODE_ENV build
+
+USER node
 WORKDIR /usr/src/app
-COPY . .
-RUN yarn install
-RUN yarn build
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+COPY --chown=node:node . .
+RUN yarn build \
+    && yarn install --production --ignore-scripts --prefer-offline
+
+PROM node:18-alpine
+
+ENV NODE_ENV production
+
+USER node
+WORKDIR /usr/src/app
+
+COPY --from=builder --chown=node:node /usr/src/app/package*.json ./
+COPY --from=builder --chown=node:node /usr/src/app/node_modules/ ./node_modules/
+COPY --from=builder --chown=node:node /usr/src/app/dist/ ./dist/
+
 EXPOSE 8080
+
 CMD ["node", "dist/main.js"]
